---
# tasks file for lbserver

- name: install haproxy package
  package:
    name: "haproxy"
    state: present


- name: copy haproxy config file
  template:
    src: "haproxy.cfg"
    dest: "/etc/haproxy/haproxy.cfg"
  notify: loadbalancer restart


- name: start haproxy service
  service:
    name: "haproxy"
    state: started
